def run(country_code: str, limit: int = 5) -> dict:
    """
    [STUB] This is a showcase handler. 
    In production, this connects to the Private Feed Engine.
    Here it returns a sample response for visualization.
    """
    samples = {
        "USA": [
            {"title": "[Sample] Global Market Shift Observed", "source": "Finance Daily", "link": "https://example.com/finance/1", "published_at": "2026-03-23T01:00:00Z"},
            {"title": "[Sample] New Tech Policy Announced", "source": "DC News", "link": "https://example.com/politics/2", "published_at": "2026-03-23T02:30:00Z"}
        ],
        "UK": [
            {"title": "[Sample] London Tech Summit Highlights", "source": "Brit Intel", "link": "https://example.com/news/3", "published_at": "2026-03-23T04:15:00Z"}
        ]
    }
    
    return {
        "country": country_code,
        "headlines": samples.get(country_code.upper(), [{"title": "Sample News Item", "source": "Demo Source"}]),
        "note": "This response is generated by the Public Showcase Stub."
    }
